language: node_js
node_js:
  - "6"
cache: yarn
script: yarn build -- --base-href /angular-deep-dive-demo
after_script: cp dist/index.html dist/404.html
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
